parameters:

- name: env
  displayName: Select Environment
  type: string
  default: dev
  values:
  - dev
- name: Change Requies ID
  displayName: Enter Change Request
  type: string
  default: 'Test'
- name: Baseversion
  displayName: Enter Baseversion for Nexus
  type: string
  default: '1.0.0-SNAPSHOT'
- name: Repository ID
  displayName: Enter Repository ID for Nexus
  type: string
  default: 'deploy-shared-01-snapshot'
  values:
  - deploy-shared-01-snapshot
  - deploy-shared-01-release
- name: Artifact ID
  displayName: Enter Artifact ID from Nexus
  type: string
  default: 'azure'
  values:
  - azure

variables:
 - template: /env-configs/${{parameters.env}}.yml

trigger:
 - none

stages:
- stage: Get_Secrets_from_KeyVault
  displayName: Get Secret
  jobs:
  # - deployment: TEST
  #   displayName: no
  #   pool: 'pipeline'
  #   environment: '${{ parameters.env }}'
  #   strategy:
  #    runOnce:
  #     deploy:
  #      steps:
  #      - script: echo Hello
  - job: Get_Secret_from_KeyVault
    pool: ${{ variables.poolname }}
    steps:
      - task: AzurePowerShell@5
        displayName: Get_Secrets_from_KeyVault
        inputs:
          azureSubscription: ${{variables.azureServiceConnection}}
          ScriptType: InlineScript
          Inline: |

          errorActionPerference: continue
          azurePowerShellVersion: latestVersion
        enabled: true
